name : Bradley Van Cleave
email : bvancleave@yahoo.com
github : bvancleave
twitter : b_van_cleave
linkedin : bradley-van-cleave-9710741

markdown : kramdown

kramdown :
    input : GFM
    sybtax_highligher : rouge

permalink: /blog/:year/:month/:day/:title
